name: Deploy React Build

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
       # step1 : Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # step2 : Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # step3 : Install Dependencies 
      - name: Install and Build
        run: npm install     

      # step4 : Build
      - name: Build 
        run: npm run build

      #step5 : Install sshpass for password-based SSH
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      # step6 : Deploy build files
      - name: verify password
        run: |
          if [ -z "$SERVER_PASSWORD" ]; then
            echo "Error: SERVER_PASSWORD is not set."
            exit 1
          else
            echo "SERVER_PASSWORD is set."
          fi
        env:
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
      
      - name: Deploy React Build
        env:
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -p "$SERVER_PASSWORD" rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -vvv" ./build/ root@your-server-ip:/path/to/your/app/